In [15]:
import torch
import torch.nn as nn
from torchinfo import summary

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.fc1 = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.fc3 = nn.Linear(2, 1)
        
    def forward(self, x):
        return self.fc3(self.fc2(self.fc1(x)))

In [16]:
## 모델 인스턴스 생성
model = Net()

print(model)

summary(model)

Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Linear: 1-3                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [9]:
# 모델 인스턴스 속성 확인
# 모델의 특정 층 추출
model.fc1

Linear(in_features=8, out_features=4, bias=True)

In [6]:
# 모델의 각 층별 w, b 텐서 정보 확인
for param in model.parameters():
    print(param, end='\n\n')

Parameter containing:
tensor([[ 0.2360,  0.2232,  0.0547, -0.0898, -0.2378,  0.1014, -0.1268, -0.0497],
        [-0.1988,  0.0514,  0.3381,  0.0259, -0.0900,  0.0892,  0.0664,  0.2452],
        [-0.0087, -0.0422, -0.1000, -0.1470, -0.0201,  0.1051, -0.0811, -0.1713],
        [-0.2780, -0.1527, -0.3285, -0.0046,  0.3396, -0.1163,  0.2641,  0.2366]],
       requires_grad=True)

Parameter containing:
tensor([-0.3225,  0.3396,  0.0839, -0.0866], requires_grad=True)

Parameter containing:
tensor([[-0.3661,  0.0062,  0.3532,  0.4357],
        [ 0.2027,  0.4222, -0.0390, -0.0889]], requires_grad=True)

Parameter containing:
tensor([-0.4224,  0.1856], requires_grad=True)

Parameter containing:
tensor([[-0.1906,  0.1401]], requires_grad=True)

Parameter containing:
tensor([-0.1395], requires_grad=True)


In [7]:
for param in model.named_parameters():
    print(param, end='\n\n')

('fc1.weight', Parameter containing:
tensor([[ 0.2360,  0.2232,  0.0547, -0.0898, -0.2378,  0.1014, -0.1268, -0.0497],
        [-0.1988,  0.0514,  0.3381,  0.0259, -0.0900,  0.0892,  0.0664,  0.2452],
        [-0.0087, -0.0422, -0.1000, -0.1470, -0.0201,  0.1051, -0.0811, -0.1713],
        [-0.2780, -0.1527, -0.3285, -0.0046,  0.3396, -0.1163,  0.2641,  0.2366]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([-0.3225,  0.3396,  0.0839, -0.0866], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[-0.3661,  0.0062,  0.3532,  0.4357],
        [ 0.2027,  0.4222, -0.0390, -0.0889]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([-0.4224,  0.1856], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[-0.1906,  0.1401]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([-0.1395], requires_grad=True))


In [14]:
for child in model.children():
    print(child, end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)


- Layer의 가중치 설정

In [11]:
# 세비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform(model.fc1.weight)

C:\Users\kdp\AppData\Local\Temp\ipykernel_9228\2264733552.py:1: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(model.fc1.weight)


Parameter containing:
tensor([[ 0.3724, -0.3341,  0.6159, -0.6610,  0.3580, -0.0042, -0.1608,  0.5505],
        [-0.4614, -0.6676, -0.1363,  0.5051, -0.5940,  0.3467, -0.4006,  0.2407],
        [-0.0962,  0.0733,  0.1173,  0.6269, -0.2814,  0.1252,  0.1848,  0.0031],
        [-0.1941,  0.5147,  0.6063, -0.0183, -0.1322,  0.6477,  0.2107, -0.0448]],
       requires_grad=True)

In [13]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_uniform(model.fc1.weight)

C:\Users\kdp\AppData\Local\Temp\ipykernel_9228\1732010444.py:2: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  nn.init.kaiming_uniform(model.fc1.weight)


Parameter containing:
tensor([[-0.6689,  0.3769,  0.5631, -0.7927, -0.7053, -0.1717, -0.3474,  0.6750],
        [-0.3627,  0.0023,  0.3938,  0.5982,  0.8492, -0.3427, -0.0183,  0.8428],
        [-0.0146,  0.2221,  0.6658,  0.1900, -0.6894, -0.8440, -0.7418, -0.7727],
        [-0.2638, -0.2478,  0.8391, -0.2636,  0.6179,  0.8289,  0.2607, -0.4430]],
       requires_grad=True)

In [18]:
torch.save(model, '../data/model/testModel.pth')

In [ ]:
torch.load