In [1]:
## 모듈 로딩
import numpy as np

In [2]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 ==> zeros()
np.zeros(2)

array([0., 0.])

In [4]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [8]:
# 1로 채워진 ndarray 객체 생성 ==> ones()
np.ones(10), np.ones(10, dtype=np.int32), np.ones((2,5), dtype=np.bool_)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [9]:
# 랜덤 데이터로 ndarray객체 생성 ==> random
np.random.randint(1, 5, (3,10))

array([[3, 3, 4, 1, 1, 3, 3, 3, 3, 2],
       [3, 2, 2, 4, 4, 3, 1, 1, 4, 4],
       [1, 2, 2, 3, 3, 1, 4, 4, 4, 4]])

In [12]:
# 0 <= 범위 < 1
np.random.rand(10), np.random.rand(5,2)

(array([0.64296   , 0.70339756, 0.76818115, 0.06229481, 0.6775806 ,
        0.06918478, 0.64905761, 0.54135393, 0.94270584, 0.31731381]),
 array([[0.71356553, 0.34856769],
        [0.74794635, 0.94076327],
        [0.9361329 , 0.11544802],
        [0.57444872, 0.87533154],
        [0.41360639, 0.22080466]]))

In [13]:
np.random.randn(5), np.random.randn(1,2,3)

(array([-0.94882738, -0.16828057, -0.19484184,  1.34137374,  0.3334333 ]),
 array([[[ 1.04558145,  0.19089378, -0.15877116],
         [ 0.33973668,  0.23933932,  0.3749222 ]]]))

In [14]:
# 랜덤 고정
np.random.seed(4)

np.random.randn(5)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [36]:
data = np.random.randn(10)
print(data)

np.random.shuffle(data)
print(data)

[-1.20344774  1.85585625  1.1770377   0.55575902  0.04229212  0.97187271
  0.62279569 -1.27804266 -1.16135207 -0.03034393]
[ 0.62279569  0.97187271 -1.20344774  1.1770377  -1.16135207  0.04229212
 -1.27804266  0.55575902  1.85585625 -0.03034393]


In [38]:
data.sum(), data.max(), data.min()

(1.5524270945670333, 1.8558562513581842, -1.2780426578904296)

In [40]:
data.argmax(), data.argmin()

(8, 6)

In [43]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape, a.shape

((1, 6), (6,))

In [159]:
np.empty(2, dtype=np.int8)

array([-80, -82], dtype=int8)