In [5]:
### 모듈 로딩
from PIL import Image
from torchvision import transforms

In [6]:
### 이미지 데이터 로딩
file = '../data/img/cat1.jpg'

In [8]:
catImg = Image.open(file)

catImg.format, catImg.height, catImg.width, catImg.mode, type(catImg)

('JPEG', 187, 270, 'RGB', PIL.JpegImagePlugin.JpegImageFile)

In [13]:
### 사용법 => (1) 인스턴스 생성 (2) 인스턴스변수 사용
to_tensor = transforms.ToTensor()

### (2) 인스턴스변수 사용
catTS = to_tensor(catImg)

### (3) 변환된 이미지 텐서 확인
print(catTS.shape, catTS.ndim)
print(catTS[0])

torch.Size([3, 187, 270]) 3
tensor([[0.1098, 0.2549, 0.4196,  ..., 0.5882, 0.5843, 0.5843],
        [0.1020, 0.2471, 0.4157,  ..., 0.5882, 0.5882, 0.5843],
        [0.0902, 0.2392, 0.4118,  ..., 0.5882, 0.5882, 0.5843],
        ...,
        [0.5176, 0.4902, 0.4902,  ..., 0.1725, 0.1647, 0.1647],
        [0.4314, 0.4039, 0.4039,  ..., 0.1725, 0.1647, 0.1647],
        [0.3569, 0.3333, 0.3294,  ..., 0.1725, 0.1647, 0.1647]])


In [37]:
#### openCV
import cv2

img = cv2.imread(filename=file)
img2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print(type(img), img.shape, img.ndim)
print(type(img2), img2.shape, img2.ndim)

### 텐서화
cat2 = to_tensor(img)
cat3 = to_tensor(img2)

print(cat2.shape, cat2.ndim)
print(cat2[0])
print()
print(cat3.shape, cat3.ndim)
print(cat3[0])

<class 'numpy.ndarray'> (187, 270, 3) 3
<class 'numpy.ndarray'> (187, 270, 3) 3
torch.Size([3, 187, 270]) 3
tensor([[0.1137, 0.2588, 0.4392,  ..., 0.2392, 0.2353, 0.2353],
        [0.1059, 0.2510, 0.4353,  ..., 0.2471, 0.2471, 0.2431],
        [0.0941, 0.2431, 0.4314,  ..., 0.2588, 0.2588, 0.2549],
        ...,
        [0.4824, 0.4549, 0.4549,  ..., 0.1255, 0.1333, 0.1412],
        [0.3961, 0.3686, 0.3686,  ..., 0.1255, 0.1333, 0.1412],
        [0.3216, 0.2980, 0.2941,  ..., 0.1255, 0.1333, 0.1412]])

torch.Size([3, 187, 270]) 3
tensor([[0.1098, 0.2549, 0.4196,  ..., 0.5882, 0.5843, 0.5843],
        [0.1020, 0.2471, 0.4157,  ..., 0.5882, 0.5882, 0.5843],
        [0.0902, 0.2392, 0.4118,  ..., 0.5882, 0.5882, 0.5843],
        ...,
        [0.5176, 0.4902, 0.4902,  ..., 0.1725, 0.1647, 0.1647],
        [0.4314, 0.4039, 0.4039,  ..., 0.1725, 0.1647, 0.1647],
        [0.3569, 0.3333, 0.3294,  ..., 0.1725, 0.1647, 0.1647]])


In [44]:
#### ==> Resizing
preprocessing = transforms.Compose(transforms=
                                   [transforms.ToTensor(),
                                    transforms.Resize(size=[2,2]),
                                    ])


In [45]:
preprocessing(img2)

tensor([[[0.5314, 0.8775],
         [0.8235, 0.3755]],

        [[0.5569, 0.7794],
         [0.8098, 0.2882]],

        [[0.5863, 0.6578],
         [0.8137, 0.1618]]])

### 이미지 데이터셋
- torchvision.ImageFolder 클래스 사용
    * 이미지 데이터 라벨링
    * 이미지 데이터 전처리

In [69]:
from torchvision.datasets import ImageFolder, DatasetFolder
import os

In [73]:
img_root = '../data/img'

imgDS = ImageFolder(root=img_root,
                    transform=preprocessing,
                    # is_valid_file=os.path.isfile
                    )