### Tensor shape 변경
- reshape(), view() : 원소 갯수가 유지됨, 기존 텐서 공유함

In [1]:
# 모듈 로딩
import torch

In [2]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3], [4,5,6]])
print(t1.shape, t1.ndim)
print(t1)

torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
# [2,3] ===> [3,2] 형태 변경 : 원소 동일 6개
t1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
# [2,3] ===> [6,1] 형태 변경 : 원소 동일 6개
t1.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [5]:
# [2,3] ===> [6,1] 형태 변경 : 원소 동일 6개
# -1 : 원소 수를 알아서 할당
t1.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [6]:
# tensor.reshape()
t1.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [7]:
# tensor.reshape()
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

- 전치 : 열<->행 변경

In [8]:
print(t1.shape)

t2=t1.T
print(t2.shape, t2.is_contiguous())

torch.Size([2, 3])
torch.Size([3, 2]) False


In [9]:
#RuntimeError: view size is not compatible with input tensor's size and stride
# t2.view(-1,6)

In [10]:
t3=t2.reshape(-1,6)
print(t3, t3.is_contiguous())

tensor([[1, 4, 2, 5, 3, 6]]) True


### 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태, 검색 방향 정보, 시작 정보

In [11]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)
print(f't1.storage() => {t1.storage()}')
print(f't1.storage_offset() => {t1.storage_offset()}')
print(f't1.stride() => {t1.stride()}')
print(f't1.is_contiguous() => {t1.is_contiguous()}')

torch.Size([2, 3]) 2
t1.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() => 0
t1.stride() => (3, 1)
t1.is_contiguous() => True


C:\Users\kdp\AppData\Local\Temp\ipykernel_4544\2935160047.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(f't1.storage() => {t1.storage()}')


In [12]:
t2 = t1.view(-1,2)
print(t2.shape, t2.ndim)
print(f't2.storage() => {t2.storage()}')
print(f't2.storage_offset() => {t2.storage_offset()}')
print(f't2.stride() => {t2.stride()}')
print(f't2.is_contiguous() => {t2.is_contiguous()}')

torch.Size([3, 2]) 2
t2.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset() => 0
t2.stride() => (2, 1)
t2.is_contiguous() => True


### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에서 차원이 1인 것 추가

In [13]:
# 데이터 생성
t1 = torch.tensor([[1,2], [3,4]])
t2 = torch.tensor([[1,2,3,4]])
t3 = torch.tensor([[[1,2,3,4]]])

In [14]:
print(f't1 => {t1.shape}, {t1.ndim}D')
print(f't2 => {t2.shape}, {t2.ndim}D')
print(f't3 => {t3.shape}, {t3.ndim}D')

t1 => torch.Size([2, 2]), 2D
t2 => torch.Size([1, 4]), 2D
t3 => torch.Size([1, 1, 4]), 3D


In [15]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
t44 = t3.squeeze(dim=0)
print(f't1 차원 축소 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}')
print(f't2 차원 축소 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}')
print(f't3 차원 축소 => {t33.shape}, {t33.ndim}D, {t33.data_ptr()}')
print(f't3 차원 축소 => {t44.shape}, {t44.ndim}D, {t44.data_ptr()}')

t1 차원 축소 => torch.Size([2, 2]), 2D, 3871296520192
t2 차원 축소 => torch.Size([4]), 1D, 3871296520320
t3 차원 축소 => torch.Size([4]), 1D, 3871296520384
t3 차원 축소 => torch.Size([1, 4]), 2D, 3871296520384


In [16]:
## 원소/요소 수 변경 없이 1 차원 증가 시키기 => torch.unsqueeze(dim)
print(f't1 정보 => {t1.shape}, {t1.ndim}, {t1.data_ptr()}')

t1 정보 => torch.Size([2, 2]), 2, 3871296520192


In [17]:
t11 = t1.unsqueeze(dim=0)
t22 = t1.unsqueeze(dim=-1)

print(f't1 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't2 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')

t1 차원 추가 => torch.Size([1, 2, 2]), 3D, 3871296520192, (4, 2, 1)
t2 차원 추가 => torch.Size([2, 2, 1]), 3D, 3871296520192, (2, 1, 1)


### Tensor 차원/형태 변경

In [20]:
t1 = torch.tensor([[[1,2], [11,22], [44,55]]])

print(t1.shape, t1.ndim)

torch.Size([1, 3, 2]) 3


In [23]:
# 2개의 차원을 변경하는 메소드
t11 = t1.transpose(0, 2)
print(f't11 => {t11.shape}, {t11.ndim}D')

t11 => torch.Size([2, 3, 1]), 3D


In [22]:
# 모든 차원을 변경하는 메소드
t22 = t1.permute(1,2,0)
print(f't22 => {t22.shape}, {t22.ndim}D')

t22 => torch.Size([3, 2, 1]), 3D


In [24]:
print(f'{t1.data_ptr()}, {t11.data_ptr()}, {t22.data_ptr()}')

3871296459520, 3871296459520, 3871296459520
