### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

- 모듈 로딩

In [60]:
import torch

- Tensor 속성 관련 함수

In [61]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def print_attribue(tensor, name):
    print(f'[Tensor {name}\'s Attribute]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}D')
    print(f' - tensor.dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data : \n{tensor.data}')

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [62]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)
t2 = torch.IntTensor([10, 20])
t3 = torch.BoolTensor([1,1,0,-1])
t4 = torch.FloatTensor([10., 20.])

In [63]:
print_attribue(t1, 't1')
print()
print_attribue(t2, 't2')
print()
print_attribue(t3, 't3')
print()
print_attribue(t4, 't4')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

[Tensor t2's Attribute]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([10, 20], dtype=torch.int32)

[Tensor t3's Attribute]
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([ True,  True, False,  True])

[Tensor t4's Attribute]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([10., 20.])


- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [64]:
t1 = torch.tensor(10)       # scaler 데이터, int64
t2 = torch.tensor(10.)      # scaler 데이터, float32

In [65]:
print_attribue(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
10


In [66]:
print_attribue(t2, 't2')

[Tensor t2's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
10.0


In [67]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = torch.tensor(10, dtype=torch.int32)    # scaler 데이터, int32
print_attribue(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
10


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0, 1 등의 값

In [68]:
# 0으로 채운 텐서
t1 = torch.zeros(5)
print_attribue(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([5])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([0., 0., 0., 0., 0.])


In [69]:
t1 = torch.zeros(5,5)
print_attribue(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [70]:
t1 = torch.zeros(5,5, dtype=torch.int8)
print_attribue(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [71]:
# 1로 채운 텐서
t1 = torch.ones((2,4), dtype=torch.int8)
print_attribue(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([2, 4])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [72]:
# 이미 존재하는 텐서와 동일한 shape로 잡고 값 채우기 => zeros_like(), ones_like(), full_like()
img = torch.tensor([[2,3,4,5,6,7], [2,3,4,5,6,7]])
print(img.shape)

torch.Size([2, 6])


In [73]:
zero_img = torch.zeros_like(img)
print(zero_img)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [74]:
one_img = torch.ones_like(img)
print(one_img)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [75]:
full_img = torch.full_like(img, 7)
print(full_img)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [76]:
# 대각선 방향으로 1채우기 => eye()
t1 = torch.eye(5)
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [77]:
t1 = torch.eye(2,3)
print(t1)

tensor([[1., 0., 0.],
        [0., 1., 0.]])


In [78]:
torch.manual_seed(12)

- Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [79]:
t5 = torch.rand(2,3)
t5

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

In [80]:
t6 = torch.randn(2,3)
t6

tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])

In [81]:
t7 = torch.randint(low=1, high=10, size=(2,3))
t7

tensor([[8, 4, 6],
        [2, 2, 2]])

- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [82]:
# 데이터생성
import numpy as np

data = np.array([11,22,33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [83]:
t1 = torch.from_numpy(data)
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [84]:
t2 = torch.as_tensor(data)
t2

tensor([11, 22, 33], dtype=torch.int32)

In [85]:
t3 = torch.tensor(data)
t3

tensor([11, 22, 33], dtype=torch.int32)

In [86]:
# ndarray 원소 변경
data[0] = 100

In [88]:
# from_numpy(), as_tensor() ==> 데이터 공유
# tensor() ==> 복사본 생성
print(data, t1, t2, t3, sep='\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
