### 텐서 연결 & 결합

In [1]:
# 모듈 로딩
import torch

In [2]:
# 텐서 데이터 생성
torch.manual_seed(12)

X = torch.rand(2, 10)
y = torch.randint(0, 2, (10,))
y2 = torch.randint(0, 2, (2, 10))

In [3]:
print(f'X => {X.shape}, {X.ndim}D')
print(f'y => {y.shape}, {y.ndim}D')
print(f'y2 => {y2.shape}, {y2.ndim}D')

X => torch.Size([2, 10]), 2D
y => torch.Size([10]), 1D
y2 => torch.Size([2, 10]), 2D


In [4]:
# tensor 연결 cat([텐서1, 텐서2, ...])
xy1 = torch.cat([X, y2], dim=1)
print(f'xy1 => {xy1.shape}, {xy1.ndim}D')

xy1 => torch.Size([2, 20]), 2D


In [5]:
# tensor 연결 cat([텐서1, 텐서2, ...])
xy2 = torch.cat([X, y2], dim=0)
print(f'xy2 => {xy2.shape}, {xy2.ndim}D')

xy2 => torch.Size([4, 10]), 2D


In [6]:
xy1.max(dim=1)

torch.return_types.max(
values=tensor([1., 1.]),
indices=tensor([10, 12]))

In [7]:
# 행 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim=1)[0]
max_index = xy1.max(dim=1)[1]

max_value, max_index

(tensor([1., 1.]), tensor([10, 12]))

In [8]:
# 열 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim=0)[0]
max_index = xy1.max(dim=0)[1]

max_value, max_index

(tensor([0.4657, 0.6948, 0.5830, 0.6318, 0.5559, 0.1272, 0.9790, 0.8443, 0.7312,
         0.7224, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000]),
 tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]))

In [9]:
import pandas as pd

data = pd.DataFrame({'A':[10,10], 'B':[20,20], 'C':[30,30]})
data

A   B   C
0  10  20  30
1  10  20  30

In [10]:
data.max()

A    10
B    20
C    30
dtype: int64

In [11]:
z = torch.randint(0, 2, (3, 2, 4))
z

tensor([[[1, 1, 1, 1],
         [0, 1, 1, 0]],

        [[1, 0, 0, 0],
         [0, 1, 1, 0]],

        [[1, 1, 1, 1],
         [0, 1, 1, 1]]])

In [13]:
z.max(dim=0)

torch.return_types.max(
values=tensor([[1, 1, 1, 1],
        [0, 1, 1, 1]]),
indices=tensor([[0, 0, 0, 0],
        [0, 0, 0, 2]]))

In [14]:
z.max(dim=1)

torch.return_types.max(
values=tensor([[1, 1, 1, 1],
        [1, 1, 1, 0],
        [1, 1, 1, 1]]),
indices=tensor([[0, 0, 0, 0],
        [0, 1, 1, 0],
        [0, 0, 0, 0]]))

In [15]:
z.max(dim=2)

torch.return_types.max(
values=tensor([[1, 1],
        [1, 1],
        [1, 1]]),
indices=tensor([[0, 1],
        [0, 1],
        [0, 1]]))