문제 1번

화면상에서 Pytorch에서 데이터를 저장하는 단위는 (Tensor)입니다.

문제 2번

다차원 형식의 자료형을 제공한다.

문제 3번

tensor.int8, tensor.int16, tensor.int32, tensor.int64...
정수형 데이터를 저장하는 데이터타입은 int로 지정하며 이때 뒤에 오는 숫자는 데이터 저장에 할당되는 메모리 크기를 bit 단위로 나타낸 것이다. 데이터 크기를 지정하지 않을 경우 기본적으로 32bit가 할당되며 이때 저장될 수 있는 데이터의 크기는 -(2^31^-1)~+(2^31^-1)이다.

문제 4번

In [21]:
import torch
from torch import tensor

In [22]:
data = tensor([10, -5, 1.4, 7, 0, -1, 0], dtype=bool)
print(f'data type :: {data.dtype}')

data type :: torch.bool


문제 5번

In [23]:
data = torch.tensor([[0 for i in range (10)]])
print(data)
print(data.shape)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
torch.Size([1, 10])


문제 6번

In [24]:
data = torch.eye(5, dtype=int)
print(data)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])


문제 7번

In [26]:
data2 = data * 3
data2

tensor([[3, 0, 0, 0, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 3]])

문제 8번

In [36]:
import numpy as np

tensor(range(7, 100, 7), dtype=torch.float32)

tensor([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84., 91., 98.])

문제 9번

문제 10번

In [54]:
data1 = torch.randint(1, 10, (6,))
data2 = data1.view((1,1,6))
data3 = data2.transpose(1,2)
data4 = data3.reshape(3,2,1)
data1, data2, data3, data4

(tensor([2, 9, 4, 7, 8, 4]),
 tensor([[[2, 9, 4, 7, 8, 4]]]),
 tensor([[[2],
          [9],
          [4],
          [7],
          [8],
          [4]]]),
 tensor([[[2],
          [9]],
 
         [[4],
          [7]],
 
         [[8],
          [4]]]))

문제 11번

In [64]:
data = {'국어':[90,70,80], '영어':[70,100,80], '수학':[99,88,77]}

score = tensor(list(data.values()), dtype=torch.float16)

for i in range(score.shape[0]):
    print(score[i].sum())
print()
    
for i in range(score.shape[1]):
    print(score[:, i].sum())
    print(score[:, i].mean())
    print(score[:, i].max())

tensor(240., dtype=torch.float16)
tensor(250., dtype=torch.float16)
tensor(264., dtype=torch.float16)

tensor(259., dtype=torch.float16)
tensor(86.3125, dtype=torch.float16)
tensor(99., dtype=torch.float16)
tensor(258., dtype=torch.float16)
tensor(86., dtype=torch.float16)
tensor(100., dtype=torch.float16)
tensor(237., dtype=torch.float16)
tensor(79., dtype=torch.float16)
tensor(80., dtype=torch.float16)


문제 12번

In [66]:
score = score
score2 = tensor([5, 2, 0.7], dtype=torch.float16)

print(score+score2)
print()
print(score.matmul(score2))

tensor([[ 95.0000,  72.0000,  80.6875],
        [ 75.0000, 102.0000,  80.6875],
        [104.0000,  90.0000,  77.6875]], dtype=torch.float16)

tensor([646., 606., 725.], dtype=torch.float16)
