### softmax(), sigmoid() 함수
- sigmoid() : y=wx+b 결과 1개 전달 ===> 반환 : 0.0 ~ 1.0 사이 값으로 변환 ==> 이진분류
- softmax() : y=wx+b 결과 여러개 전달 ===> 반환 : 여러개의 결과값의 합이 1.0이 되도록 변환 ==> 다중분류

In [6]:
## 모둘 로딩
import torch                            # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F         # 파이토치 인공신경망 관련 함수들

In [7]:
# 임의 데이터 생성
data1 = torch.tensor([1,2,1,1,2], dtype=torch.float)
data1.shape

torch.Size([5])

In [8]:
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [9]:
data2 = data1.unsqueeze(dim=1)
data2.shape, data2

(torch.Size([5, 1]),
 tensor([[1.],
         [2.],
         [1.],
         [1.],
         [2.]]))

In [10]:
F.softmax(data2, dim=1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])