### 인공신경망 모델 클래스 만들기
- 부모 클래스 : nn.Module 상속 받음
- 필수 오버라이딩 메소드 : __init(), forward()

[1] 모듈로딩 

In [1]:
import torch
import torch.nn as nn

In [22]:
# 로지스틱회귀 모델 클래스 생성
# - Linear + sigmoid

class LogicLinear(nn.Module):
    # 모델 구조 설정
    def __init__(self, in_, out_):
        super().__init__()
        self.layer1 = nn.Linear(in_, 10)
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(10, out_)
        self.sigmoid2 = nn.Sigmoid()
        
    # 순방향 학습 진행 콜백함수
    def forward(self, x):
        x = self.layer1(x)
        x = self.sigmoid1(x)
        x = self.layer2(x)
        x = self.sigmoid2(x)
        return x

In [23]:
# 모델 인스턴스 생성
l1 = LogicLinear(4, 10)
l1

LogicLinear(
  (layer1): Linear(in_features=4, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=10, bias=True)
  (sigmoid2): Sigmoid()
)

In [24]:
for param in l1.parameters():
    print(param)

Parameter containing:
tensor([[-0.4791, -0.0319, -0.0185, -0.4627],
        [ 0.1904, -0.3915, -0.3979,  0.3357],
        [-0.4480,  0.4830, -0.4940, -0.1644],
        [ 0.0681,  0.0026,  0.3994,  0.4961],
        [ 0.3947, -0.3807,  0.1543,  0.2295],
        [ 0.2032, -0.4267,  0.1731,  0.0754],
        [-0.1697, -0.1096, -0.4992,  0.3694],
        [-0.4478, -0.0450, -0.0998, -0.4130],
        [ 0.4853,  0.2500, -0.4420,  0.0624],
        [ 0.2206, -0.2383, -0.3688,  0.2490]], requires_grad=True)
Parameter containing:
tensor([-0.3955, -0.0965,  0.0406,  0.1289,  0.4754, -0.4782, -0.1613, -0.0520,
        -0.0976, -0.0252], requires_grad=True)
Parameter containing:
tensor([[-0.1885, -0.1732,  0.2732,  0.0712,  0.2177,  0.0493, -0.1542, -0.3128,
         -0.0037, -0.1501],
        [ 0.1817,  0.2825, -0.2543,  0.3158, -0.1703, -0.0460,  0.1930,  0.2880,
         -0.1912, -0.0729],
        [-0.2015, -0.1211, -0.2862,  0.1821, -0.0746,  0.2915,  0.2928,  0.1409,
         -0.0823, -0.1326],